Add verify

diff --git a/.github/workflows/artifact-attestation.yml b/.github/workflows/artifact-attestation.yml
--- a/.github/workflows/artifact-attestation.yml
+++ b/.github/workflows/artifact-attestation.yml
@@ -52,8 +52,15 @@ jobs:
           name: example-artifact
       - name: Validate artifact attestation
         run: |
-          ATTESTATION_OUTPUT=$(gh attestation verify ${{ env.ARTIFACT_PATH }} --owner christian-calabrese --signer-workflow christian-calabrese/ArkaPoyd/.github/workflows/artifact-attestation.yml --format=json)
-          echo "ATTESTATION_OUTPUT: $ATTESTATION_OUTPUT"
+          echo "[INFO] Inizio validazione attestation..."
+          gh attestation verify ${{ env.ARTIFACT_PATH }} --owner christian-calabrese --signer-workflow christian-calabrese/ArkaPoyd/.github/workflows/artifact-attestation.yml
+          STATUS=$?
+          if [ $STATUS -eq 0 ]; then
+            echo "[SUCCESS] Attestazione valida!"
+          else
+            echo "[ERROR] Attestazione NON valida!"
+            exit $STATUS
+          fi
         env:
           ARTIFACT_PATH: "./artifact.txt"
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
